### ISSUE TITLE
Plugin breaks Orders page

### ISSUE THREAD

**Issue by glitchedmob** [superbigco/craft-batchpdfexport#2]
After upgrading this plugin to the newest version (1.0.2) I get an error on the Commerce orders page. After looking into the network tab of devtools I can see that the url `index.php?p=admin/actions/element-indexes/get-elements` is returning a 500 error with this JSON response `{"error":"Class 'superbig\\batchpdfexport\\models\\Settings' not found"}`

Craft Commerce v2.0.4
Craft CMS v3.1.12

**Comment by bwlng** [comment]
I was just coming to post the same issue :)

If I disable the plugin, the Commerce order index loads as normal. PDFs from a single order export correctly with Commerce’s native PDF export.

I tried creating an empty `batch-pdf-export.php` in my config folder, but still get the same error as above.

craftcms/commerce 2.0.4
craftcms/cms 3.1.12

**Comment by sjelfull** [comment]
Sorry about that - forgot to actually commit the model 😱 will have a fix out in a second.

**Comment by bwlng** [comment]
Thanks!
