### ISSUE TITLE
Conflicting iio/libmergepdf with Commerce 3.4

### ISSUE THREAD

**Issue by tokerseyRB** [superbigco/craft-batchpdfexport#7]
### Describe the bug
Craft Commerce has updated the dependency of libmergepdf to be ~4.0, this is causing a conflict with batchpdfexports being set to ~3.0. So, I am unable to update Craft Commerce to latest version with the dependency conflict. Could the version be updated in Batch PDF Export to be consistent with Craft Commerce? 

### To reproduce
Steps to reproduce the behaviour:
1. Set Craft Commerce to 3.4.0 in composer.json
2. `composer update`
3. See error message:

`Problem 1
    - Root composer.json requires craftcms/digital-products 2.4.3.1 -> satisfiable by craftcms/digital-products[2.4.3.1].
    - Conclusion: don't install iio/libmergepdf 4.0.2 (conflict analysis result)
    - Conclusion: don't install iio/libmergepdf[4.0.3] | install iio/libmergepdf[3.1.1] (conflict analysis result)
    - Conclusion: don't install iio/libmergepdf 3.1.1 (conflict analysis result)
    - Conclusion: don't install iio/libmergepdf 4.0.4 (conflict analysis result)
    - craftcms/digital-products 2.4.3.1 requires craftcms/commerce ^2.1|^3.0 -> satisfiable by craftcms/commerce[3.4.0-beta.1, 3.4.0, 3.4.0.1, 3.4.x-dev].
    - Conclusion: don't install craftcms/commerce 3.4.0-beta.1 (conflict analysis result)
    - Conclusion: don't install craftcms/commerce 3.4.0 (conflict analysis result)
    - Conclusion: don't install craftcms/commerce 3.4.0.1 (conflict analysis result)
    - Root composer.json requires superbig/craft-batchpdfexport ^1.0.4 -> satisfiable by superbig/craft-batchpdfexport[1.0.4].
    - craftcms/commerce 3.4.x-dev requires iio/libmergepdf ^4.0 -> satisfiable by iio/libmergepdf[4.0.0, ..., 4.0.4].
    - You can only install one version of a package, so only one of these can be installed: iio/libmergepdf[3.0.0, 3.1.0, 3.1.1, 4.0.0, ..., 4.0.4].
    - superbig/craft-batchpdfexport 1.0.4 requires iio/libmergepdf ~3.0 -> satisfiable by iio/libmergepdf[3.0.0, 3.1.0, 3.1.1].
    - Conclusion: don't install iio/libmergepdf 3.1.0 (conflict analysis result)`

### Expected behaviour
Successful install of Craft Commerce 3.4

### Versions
- Plugin version: 1.0.4
- Craft version: 3.7.3.2

**Comment by vanmeeter** [comment]
Hello, I was just wondering if there has been any progress on this issue. I am also having this issue updating a client's site with commerce and this plugin. Thanks.

**Comment by maxpdesign** [comment]
Hello, any update about this? I also have this issue with a client's site and it is preventing further updates.

**Comment by tokersey** [comment]
Project seems to be abandoned.

**Comment by maxpdesign** [comment]
@tokersey I think so too. Maybe this will help someone else:
I uninstalled and deleted the plugin. Then I could successfully update commerce to version 3.4.19. Once I updated to commerce 3.4.19 the functionality this plugin provided seems to be a feature in the commerce plugin itself now. So I think it is safe to just delete this plugin if you are updating commerce.

**Comment by sjelfull** [comment]
As @maxpdesign noted its now part of core Commerce.
